### ISSUE TITLE
Create ssh tunnel on port 22?

### ISSUE THREAD

**Issue by tobyworks** [ThePicklenat0r/hassio-ngrok#22]
How do i configure an additional tunnel for port 22 ?

**Comment by ThePicklenat0r** [comment]
For this you would probably need to use a tcp tunnel. You would set the proto to tcp and the addr to 22. 

The addon was made using the official ngrok client, so the configuration in the addon is essentially identical to the official client's configuration. You can use their documentation for help on how to setup a specific tunnel https://ngrok.com/docs#tunnel-definitions
